[background]
path = "/home/pugzarecute/Documents/dotfiles/images/Background.png"
fit = "Contain"

[GTK]
application_prefer_dark_theme = true

font_name = "VT323 16"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
